//
//  MainViewModel.swift
//  WeatherNow
//
//  Created by ELMIR ISMAYILZADA on 06.06.23.
//

import Foundation
import SwiftUI

class MainViewModel: ObservableObject {

    @Published var weather: WeatherModel?
        
    func getData(completion: @escaping()->()) {
//        NetworkManager.shared.getWeather { weather in
//            DispatchQueue.main.async {
//                self.weather = weather
//                completion()
//            }
//        }
        guard let jsonData = jsonString.data(using: .utf8) else { return }
        
        let weather = try? JSONDecoder().decode(WeatherModel.self, from: jsonData)
        self.weather = weather
        completion()
    }
    
    let jsonString = """
{
    "location": {
        "name": "Baku",
        "region": "Baki",
        "country": "Azerbaijan",
        "lat": 40.4,
        "lon": 49.88,
        "tz_id": "Asia/Baku",
        "localtime_epoch": 1687464311,
        "localtime": "2023-06-23 0:05"
    },
    "current": {
        "last_updated_epoch": 1687464000,
        "last_updated": "2023-06-23 00:00",
        "temp_c": 23.0,
        "temp_f": 73.4,
        "is_day": 0,
        "condition": {
            "text": "Clear",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
            "code": 1000
        },
        "wind_mph": 9.4,
        "wind_kph": 15.1,
        "wind_degree": 350,
        "wind_dir": "N",
        "pressure_mb": 1015.0,
        "pressure_in": 29.97,
        "precip_mm": 0.0,
        "precip_in": 0.0,
        "humidity": 65,
        "cloud": 0,
        "feelslike_c": 24.7,
        "feelslike_f": 76.5,
        "vis_km": 10.0,
        "vis_miles": 6.0,
        "uv": 1.0,
        "gust_mph": 19.7,
        "gust_kph": 31.7
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2023-06-23",
                "date_epoch": 1687478400,
                "day": {
                    "maxtemp_c": 28.1,
                    "maxtemp_f": 82.6,
                    "mintemp_c": 22.9,
                    "mintemp_f": 73.2,
                    "avgtemp_c": 24.7,
                    "avgtemp_f": 76.4,
                    "maxwind_mph": 18.3,
                    "maxwind_kph": 29.5,
                    "totalprecip_mm": 0.0,
                    "totalprecip_in": 0.0,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 10.0,
                    "avgvis_miles": 6.0,
                    "avghumidity": 52.0,
                    "daily_will_it_rain": 0,
                    "daily_chance_of_rain": 0,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "uv": 6.0
                },
                "astro": {
                    "sunrise": "05:11 AM",
                    "sunset": "08:14 PM",
                    "moonrise": "09:44 AM",
                    "moonset": "11:54 PM",
                    "moon_phase": "Waxing Crescent",
                    "moon_illumination": "20",
                    "is_moon_up": 0,
                    "is_sun_up": 0
                },
                "hour": [
                    {
                        "time_epoch": 1687464000,
                        "time": "2023-06-23 00:00",
                        "temp_c": 23.4,
                        "temp_f": 74.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 14.8,
                        "wind_kph": 23.8,
                        "wind_degree": 15,
                        "wind_dir": "NNE",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.98,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 50,
                        "cloud": 46,
                        "feelslike_c": 24.9,
                        "feelslike_f": 76.8,
                        "windchill_c": 23.4,
                        "windchill_f": 74.1,
                        "heatindex_c": 24.9,
                        "heatindex_f": 76.8,
                        "dewpoint_c": 12.4,
                        "dewpoint_f": 54.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 20.8,
                        "gust_kph": 33.5,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1687467600,
                        "time": "2023-06-23 01:00",
                        "temp_c": 23.5,
                        "temp_f": 74.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 14.1,
                        "wind_kph": 22.7,
                        "wind_degree": 6,
                        "wind_dir": "N",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.0,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 51,
                        "cloud": 44,
                        "feelslike_c": 24.9,
                        "feelslike_f": 76.8,
                        "windchill_c": 23.5,
                        "windchill_f": 74.3,
                        "heatindex_c": 24.9,
                        "heatindex_f": 76.8,
                        "dewpoint_c": 12.7,
                        "dewpoint_f": 54.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 19.7,
                        "gust_kph": 31.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1687471200,
                        "time": "2023-06-23 02:00",
                        "temp_c": 23.5,
                        "temp_f": 74.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 14.8,
                        "wind_kph": 23.8,
                        "wind_degree": 13,
                        "wind_dir": "NNE",
                        "pressure_mb": 1016.0,
                        "pressure_in": 29.99,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 51,
                        "cloud": 33,
                        "feelslike_c": 25.0,
                        "feelslike_f": 77.0,
                        "windchill_c": 23.5,
                        "windchill_f": 74.3,
                        "heatindex_c": 25.0,
                        "heatindex_f": 77.0,
                        "dewpoint_c": 12.7,
                        "dewpoint_f": 54.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 21.3,
                        "gust_kph": 34.2,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1687474800,
                        "time": "2023-06-23 03:00",
                        "temp_c": 23.5,
                        "temp_f": 74.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 14.5,
                        "wind_kph": 23.4,
                        "wind_degree": 11,
                        "wind_dir": "NNE",
                        "pressure_mb": 1016.0,
                        "pressure_in": 29.99,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 51,
                        "cloud": 43,
                        "feelslike_c": 25.0,
                        "feelslike_f": 77.0,
                        "windchill_c": 23.5,
                        "windchill_f": 74.3,
                        "heatindex_c": 25.0,
                        "heatindex_f": 77.0,
                        "dewpoint_c": 12.8,
                        "dewpoint_f": 55.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 20.8,
                        "gust_kph": 33.5,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1687478400,
                        "time": "2023-06-23 04:00",
                        "temp_c": 23.3,
                        "temp_f": 73.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 15.2,
                        "wind_kph": 24.5,
                        "wind_degree": 14,
                        "wind_dir": "NNE",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.0,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 52,
                        "cloud": 46,
                        "feelslike_c": 24.9,
                        "feelslike_f": 76.8,
                        "windchill_c": 23.3,
                        "windchill_f": 73.9,
                        "heatindex_c": 24.9,
                        "heatindex_f": 76.8,
                        "dewpoint_c": 13.0,
                        "dewpoint_f": 55.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 21.9,
                        "gust_kph": 35.3,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1687482000,
                        "time": "2023-06-23 05:00",
                        "temp_c": 22.9,
                        "temp_f": 73.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 14.5,
                        "wind_kph": 23.4,
                        "wind_degree": 14,
                        "wind_dir": "NNE",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.01,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 57,
                        "cloud": 45,
                        "feelslike_c": 24.8,
                        "feelslike_f": 76.6,
                        "windchill_c": 22.9,
                        "windchill_f": 73.2,
                        "heatindex_c": 24.8,
                        "heatindex_f": 76.6,
                        "dewpoint_c": 13.8,
                        "dewpoint_f": 56.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 21.0,
                        "gust_kph": 33.8,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1687485600,
                        "time": "2023-06-23 06:00",
                        "temp_c": 22.9,
                        "temp_f": 73.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 14.1,
                        "wind_kph": 22.7,
                        "wind_degree": 10,
                        "wind_dir": "N",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.03,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 59,
                        "cloud": 31,
                        "feelslike_c": 24.9,
                        "feelslike_f": 76.8,
                        "windchill_c": 22.9,
                        "windchill_f": 73.2,
                        "heatindex_c": 24.9,
                        "heatindex_f": 76.8,
                        "dewpoint_c": 14.4,
                        "dewpoint_f": 57.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 19.9,
                        "gust_kph": 32.0,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1687489200,
                        "time": "2023-06-23 07:00",
                        "temp_c": 23.1,
                        "temp_f": 73.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 14.5,
                        "wind_kph": 23.4,
                        "wind_degree": 4,
                        "wind_dir": "N",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.05,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 60,
                        "cloud": 25,
                        "feelslike_c": 25.0,
                        "feelslike_f": 77.0,
                        "windchill_c": 23.1,
                        "windchill_f": 73.6,
                        "heatindex_c": 25.0,
                        "heatindex_f": 77.0,
                        "dewpoint_c": 15.0,
                        "dewpoint_f": 59.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 19.7,
                        "gust_kph": 31.7,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1687492800,
                        "time": "2023-06-23 08:00",
                        "temp_c": 23.4,
                        "temp_f": 74.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 15.4,
                        "wind_kph": 24.8,
                        "wind_degree": 2,
                        "wind_dir": "N",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.05,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 61,
                        "cloud": 23,
                        "feelslike_c": 25.1,
                        "feelslike_f": 77.2,
                        "windchill_c": 23.4,
                        "windchill_f": 74.1,
                        "heatindex_c": 25.1,
                        "heatindex_f": 77.2,
                        "dewpoint_c": 15.3,
                        "dewpoint_f": 59.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 20.1,
                        "gust_kph": 32.4,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1687496400,
                        "time": "2023-06-23 09:00",
                        "temp_c": 23.7,
                        "temp_f": 74.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 16.3,
                        "wind_kph": 26.3,
                        "wind_degree": 359,
                        "wind_dir": "N",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.05,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 61,
                        "cloud": 22,
                        "feelslike_c": 25.3,
                        "feelslike_f": 77.5,
                        "windchill_c": 23.7,
                        "windchill_f": 74.7,
                        "heatindex_c": 25.3,
                        "heatindex_f": 77.5,
                        "dewpoint_c": 15.7,
                        "dewpoint_f": 60.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 20.4,
                        "gust_kph": 32.8,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1687500000,
                        "time": "2023-06-23 10:00",
                        "temp_c": 24.2,
                        "temp_f": 75.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 17.4,
                        "wind_kph": 28.1,
                        "wind_degree": 358,
                        "wind_dir": "N",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.05,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 60,
                        "cloud": 22,
                        "feelslike_c": 25.6,
                        "feelslike_f": 78.1,
                        "windchill_c": 24.2,
                        "windchill_f": 75.6,
                        "heatindex_c": 25.6,
                        "heatindex_f": 78.1,
                        "dewpoint_c": 15.8,
                        "dewpoint_f": 60.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 20.6,
                        "gust_kph": 33.1,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1687503600,
                        "time": "2023-06-23 11:00",
                        "temp_c": 25.4,
                        "temp_f": 77.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 18.3,
                        "wind_kph": 29.5,
                        "wind_degree": 1,
                        "wind_dir": "N",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.06,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 58,
                        "cloud": 23,
                        "feelslike_c": 26.5,
                        "feelslike_f": 79.7,
                        "windchill_c": 25.4,
                        "windchill_f": 77.7,
                        "heatindex_c": 26.5,
                        "heatindex_f": 79.7,
                        "dewpoint_c": 16.5,
                        "dewpoint_f": 61.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 21.0,
                        "gust_kph": 33.8,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1687507200,
                        "time": "2023-06-23 12:00",
                        "temp_c": 25.9,
                        "temp_f": 78.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 18.3,
                        "wind_kph": 29.5,
                        "wind_degree": 10,
                        "wind_dir": "N",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.06,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 56,
                        "cloud": 22,
                        "feelslike_c": 26.9,
                        "feelslike_f": 80.4,
                        "windchill_c": 25.9,
                        "windchill_f": 78.6,
                        "heatindex_c": 26.9,
                        "heatindex_f": 80.4,
                        "dewpoint_c": 16.5,
                        "dewpoint_f": 61.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 21.0,
                        "gust_kph": 33.8,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1687510800,
                        "time": "2023-06-23 13:00",
                        "temp_c": 26.6,
                        "temp_f": 79.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 17.9,
                        "wind_kph": 28.8,
                        "wind_degree": 18,
                        "wind_dir": "NNE",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.05,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 53,
                        "cloud": 20,
                        "feelslike_c": 27.4,
                        "feelslike_f": 81.3,
                        "windchill_c": 26.6,
                        "windchill_f": 79.9,
                        "heatindex_c": 27.4,
                        "heatindex_f": 81.3,
                        "dewpoint_c": 16.4,
                        "dewpoint_f": 61.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 20.6,
                        "gust_kph": 33.1,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1687514400,
                        "time": "2023-06-23 14:00",
                        "temp_c": 26.5,
                        "temp_f": 79.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 18.1,
                        "wind_kph": 29.2,
                        "wind_degree": 19,
                        "wind_dir": "NNE",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.04,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 51,
                        "cloud": 17,
                        "feelslike_c": 27.2,
                        "feelslike_f": 81.0,
                        "windchill_c": 26.5,
                        "windchill_f": 79.7,
                        "heatindex_c": 27.2,
                        "heatindex_f": 81.0,
                        "dewpoint_c": 15.5,
                        "dewpoint_f": 59.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 20.8,
                        "gust_kph": 33.5,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1687518000,
                        "time": "2023-06-23 15:00",
                        "temp_c": 28.1,
                        "temp_f": 82.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 17.9,
                        "wind_kph": 28.8,
                        "wind_degree": 21,
                        "wind_dir": "NNE",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.03,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 49,
                        "cloud": 15,
                        "feelslike_c": 28.8,
                        "feelslike_f": 83.8,
                        "windchill_c": 28.1,
                        "windchill_f": 82.6,
                        "heatindex_c": 28.8,
                        "heatindex_f": 83.8,
                        "dewpoint_c": 16.5,
                        "dewpoint_f": 61.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 20.6,
                        "gust_kph": 33.1,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1687521600,
                        "time": "2023-06-23 16:00",
                        "temp_c": 26.8,
                        "temp_f": 80.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 18.1,
                        "wind_kph": 29.2,
                        "wind_degree": 21,
                        "wind_dir": "NNE",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.02,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 48,
                        "cloud": 13,
                        "feelslike_c": 27.3,
                        "feelslike_f": 81.1,
                        "windchill_c": 26.8,
                        "windchill_f": 80.2,
                        "heatindex_c": 27.3,
                        "heatindex_f": 81.1,
                        "dewpoint_c": 14.9,
                        "dewpoint_f": 58.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 20.8,
                        "gust_kph": 33.5,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1687525200,
                        "time": "2023-06-23 17:00",
                        "temp_c": 26.9,
                        "temp_f": 80.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 17.9,
                        "wind_kph": 28.8,
                        "wind_degree": 21,
                        "wind_dir": "NNE",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.01,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 47,
                        "cloud": 11,
                        "feelslike_c": 27.2,
                        "feelslike_f": 81.0,
                        "windchill_c": 26.9,
                        "windchill_f": 80.4,
                        "heatindex_c": 27.2,
                        "heatindex_f": 81.0,
                        "dewpoint_c": 14.5,
                        "dewpoint_f": 58.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 20.6,
                        "gust_kph": 33.1,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1687528800,
                        "time": "2023-06-23 18:00",
                        "temp_c": 26.8,
                        "temp_f": 80.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 17.4,
                        "wind_kph": 28.1,
                        "wind_degree": 17,
                        "wind_dir": "NNE",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.01,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 44,
                        "cloud": 12,
                        "feelslike_c": 27.0,
                        "feelslike_f": 80.6,
                        "windchill_c": 26.8,
                        "windchill_f": 80.2,
                        "heatindex_c": 27.0,
                        "heatindex_f": 80.6,
                        "dewpoint_c": 13.6,
                        "dewpoint_f": 56.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 20.1,
                        "gust_kph": 32.4,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1687532400,
                        "time": "2023-06-23 19:00",
                        "temp_c": 26.7,
                        "temp_f": 80.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 17.0,
                        "wind_kph": 27.4,
                        "wind_degree": 13,
                        "wind_dir": "NNE",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.01,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 43,
                        "cloud": 11,
                        "feelslike_c": 26.9,
                        "feelslike_f": 80.4,
                        "windchill_c": 26.7,
                        "windchill_f": 80.1,
                        "heatindex_c": 26.9,
                        "heatindex_f": 80.4,
                        "dewpoint_c": 13.2,
                        "dewpoint_f": 55.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 19.5,
                        "gust_kph": 31.3,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1687536000,
                        "time": "2023-06-23 20:00",
                        "temp_c": 24.0,
                        "temp_f": 75.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 17.0,
                        "wind_kph": 27.4,
                        "wind_degree": 7,
                        "wind_dir": "N",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.01,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 44,
                        "cloud": 11,
                        "feelslike_c": 25.0,
                        "feelslike_f": 77.0,
                        "windchill_c": 24.0,
                        "windchill_f": 75.2,
                        "heatindex_c": 25.0,
                        "heatindex_f": 77.0,
                        "dewpoint_c": 11.1,
                        "dewpoint_f": 52.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 21.5,
                        "gust_kph": 34.6,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1687539600,
                        "time": "2023-06-23 21:00",
                        "temp_c": 23.7,
                        "temp_f": 74.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 17.2,
                        "wind_kph": 27.7,
                        "wind_degree": 3,
                        "wind_dir": "N",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.01,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 45,
                        "cloud": 12,
                        "feelslike_c": 24.9,
                        "feelslike_f": 76.8,
                        "windchill_c": 23.7,
                        "windchill_f": 74.7,
                        "heatindex_c": 24.9,
                        "heatindex_f": 76.8,
                        "dewpoint_c": 11.1,
                        "dewpoint_f": 52.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 22.1,
                        "gust_kph": 35.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1687543200,
                        "time": "2023-06-23 22:00",
                        "temp_c": 23.6,
                        "temp_f": 74.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 17.4,
                        "wind_kph": 28.1,
                        "wind_degree": 2,
                        "wind_dir": "N",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.01,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 45,
                        "cloud": 13,
                        "feelslike_c": 24.8,
                        "feelslike_f": 76.6,
                        "windchill_c": 23.6,
                        "windchill_f": 74.5,
                        "heatindex_c": 24.8,
                        "heatindex_f": 76.6,
                        "dewpoint_c": 11.1,
                        "dewpoint_f": 52.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 22.4,
                        "gust_kph": 36.0,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1687546800,
                        "time": "2023-06-23 23:00",
                        "temp_c": 23.5,
                        "temp_f": 74.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 17.0,
                        "wind_kph": 27.4,
                        "wind_degree": 4,
                        "wind_dir": "N",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.01,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 45,
                        "cloud": 14,
                        "feelslike_c": 24.8,
                        "feelslike_f": 76.6,
                        "windchill_c": 23.5,
                        "windchill_f": 74.3,
                        "heatindex_c": 24.8,
                        "heatindex_f": 76.6,
                        "dewpoint_c": 11.0,
                        "dewpoint_f": 51.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 21.7,
                        "gust_kph": 34.9,
                        "uv": 1.0
                    }
                ]
            }
        ]
    }
}
"""
}
